### ISSUE TITLE
Junos XML Attributes are not parsed

### ISSUE THREAD

**Issue by jorgeNeutrona** [Juniper/jxmlease#18]
Part of XML RPC:

                      <family>
                           <inet>
                              <filter>
                                 <input inactive="inactive"> --> not parsed in OrderedDict
                                    <filter-name>re-protection</filter-name>
                                 </input>
                              </filter>
                              <address>

XMLCDATANode(xml_attrs=OrderedDict()

The OrderedDict is empty 

 pprint(root['node']['result']['rpc-reply']['data']['configuration']['interfaces']['interface']['unit'][
                            1]['family']['inet']['filter'].get_xml_attrs())

output: OrderedDict()

**Comment by stacywsmith** [comment]
In your partial XML output, the XML attribute is on the `<input>` element, not the `<filter>` element.

```
user@h0:~$ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> xml = """
...         <family>
...                        <inet>
...                           <filter>
...                              <input inactive="inactive"> --> not parsed in OrderedDict
...                                 <filter-name>re-protection</filter-name>
...                              </input>
...                           </filter>
...                           <address>
... </address>
... </inet>
... </family>
... """
>>> import jxmlease
>>> root = jxmlease.parse(xml)
>>> root['family']['inet']['filter']['input'].get_xml_attrs()
OrderedDict([(u'inactive', u'inactive')])
>>> 
```

**Comment by jorgeNeutrona** [comment]
Thanks! Worked FIne
