### ISSUE TITLE
Fails to correctly handle array of empty nodes

### ISSUE THREAD

**Issue by montsaroff-res** [Juniper/jxmlease#24]
Given
`<data1  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
    <items>
        <item name="item1" time="now1"></item>
        <item name="item2" time="now2"></item>
    </items>`

The code 
`    tree_text = open('test.xml', 'r').read()
    parse = jxmlease.Parser()
    eparse = jxmlease.EtreeParser()
    adict = parse(tree_text)
    adict.prettyprint()
    print(f"['data1']['items']['item'][0]: {adict['data1']['items']['item'][0].get_xml_attrs()}")
    print(f"['data1']['items']['item'][1]: {adict['data1']['items']['item'][1].get_xml_attrs()}")
 `
Renders: 
{'data1': {'a': {'b': 'c'},
           'fred': {'ethel': 'ethel_data'},
           'items': {'item': ['', '']}}}
['data1']['items']['item'][0]: OrderedDict([('name', 'item2'), ('time', 'now2')])
['data1']['items']['item'][1]: OrderedDict([('name', 'item2'), ('time', 'now2')])

That is the last nodes attributes are the only ones provided.

**Comment by vnitinv** [comment]
@montsaroff-res We will check this and get back to you.

**Comment by hroskes** [comment]
I just came across the same bug.  Is there any update on this?

**Comment by hroskes** [comment]
Actually, I think #23 fixes this!  Is there any way we can get a new release on pypi?

**Comment by ydnath** [comment]
@hroskes Will you be able to install from GitHub and confirm if (#23) fixes your issue?

Once you confirm I will make a release.

**Comment by hroskes** [comment]
@ydnath yes, I'd already installed from github and it works great.  Thank you!

**Comment by ydnath** [comment]
#23 fixes these

**Comment by vnitinv** [comment]
@stacywsmith Hi Stacy, Looks like we dont have permission to release this repo to PyPI?
Can you please check if we can get the access details for https://pypi.org/user/jxmlease/
